services:
  - type: web
    name: tabonet
    runtime: docker
    plan: free
    region: singapore
    branch: develop
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        value: tabonet
      - key: MYSQL_ATTR_SSL_CA
        value: database/isrgrootx1.pem
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
